### ISSUE TITLE
Forge 1.12.2-14.23.2.2647 breaks unloader

### ISSUE THREAD

**Issue by evhub** [Unnoen/Unloader#2]
I updated forge and noticed that unloader seemed to no longer be working, as `/forge tps` was now showing a bunch of dimensions that didn't used to be there. After a bit of binary search over different forge versions, I think the issue is being caused by forge build 1.12.2-14.23.2.2647, which included the change

> bs2609: Check for empty dimensions outside of chunk unloading loop, culling worlds without needing chunk unloads to trigger it. (#4704)

It seems like this change should just replace unloader, but since all the dimensions still show up under `/forge tps`, the forge change doesn't seem to be doing anything. Thus, an unloader update with compatibility for the new forge version would be greatly appreciated.

**Comment by Unnoen** [comment]
Sorry for the delay! 

It seems when a dimension is queued to unload, and gets queued again, it resets the wait time. 

[I actually had this check previously](https://github.com/Unnoen/Unloader/commit/892e276fa54adf250f4ecc781123785c10dc5019) but removed it to make Unloader cross-version compatible. I'll push an update for 1.12.2 with the check back in.

**Comment by Unnoen** [comment]
Fixed in commit daf0aa952237f5c96c55e243f1c5ed9a1e752e0b for 1.12.2.

You should see it on [the Curseforge page](https://minecraft.curseforge.com/projects/unloader) soon.

Again, sorry for the delay!

**Comment by Yoosk** [comment]
Doesn't seem to be working on our server with forge-1.12.2-14.23.3.2678. Any way to check if its trying do do anything?

**Comment by Unnoen** [comment]
Fixed for real now. https://github.com/Unnoen/Unloader/commit/90832b4eb2b35cc3b9342cd797408094db514fd0
