### ISSUE TITLE
[Feature Request] Dimension Blacklist

### ISSUE THREAD

**Issue by InjuredWolf** [Unnoen/Unloader#3]
Certain mods (like mystcraft for its profiling) need their dimension to remain loaded. If I could blacklist dimensions to unload that would be really helpful

**Comment by Unnoen** [comment]
Yeah this has been on the TODO list for quite some time, but with personal affairs I haven't really been able to dedicate time to it.

On the plus side, I should have some free time coming up and I'll definitely get something out. I'm planning on having users be able to filter via dimension ID or custom regex filtering. (e.g. being able to blacklist all dimensions starting with "MYST" or "RFT" for example.)

I'll keep this issue open until I push the update.

**Comment by Unnoen** [comment]
Just pushed an update that adds a config file with a blacklist! (It uses RegEx too!) https://github.com/Unnoen/Unloader/commit/db13984dd4b16686b561b2ad0e8d4bb4490fbfe9

For example if you wanted to blacklist all dimensions starting with `myst` just add `myst.*` to the blacklist.

**Comment by InjuredWolf** [comment]
Sweet! sounds great!
